### ISSUE TITLE
Icone calendrier invisible sur chromium quand on utilise un input datetime-local natif

### ISSUE THREAD

**Issue by ThomasPrioul** [ThomasPrioul/mdl-angular-libs#76]
Une input de ce type :
```html
<mat-form-field>
  <mat-label>Time picker</mat-label>
  <input matInput type="datetime-local" />
</mat-form-field>
```

N'a pas d'icone par défaut sur chromium, alors qu'elle est visible dans firefox :
![Image](https://github.com/user-attachments/assets/421fffae-4908-428f-add9-24f868a35a03)

La solution est de mettre une class custom :

```css
/* dans styles.css */
.mdc-text-field__input.with-icon::-webkit-calendar-picker-indicator {
  display: unset;
}
```

Puis de s'en servir dans le code :
```html
<mat-form-field>
  <mat-label>Time picker</mat-label>
  <input matInput class="with-icon" type="datetime-local" />
</mat-form-field>
```

Maintenant l'icone apparait sur chromium :

![Image](https://github.com/user-attachments/assets/570c5958-6da4-4e78-b0b7-a997706aeaa0)
